# Generated by Django 5.2.8 on 2025-11-07 13:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quitus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_quitus', models.CharField(max_length=30, unique=True, verbose_name='QUITUS N°')),
                ('date_validite', models.DateField(default=django.utils.timezone.now, verbose_name="VALABLE JUSQU'AU")),
                ('nom_prenoms', models.CharField(max_length=100, verbose_name='NOM ET PRENOMS')),
                ('raison_sociale', models.CharField(max_length=100, verbose_name='NOM / RAISON SOCIALE')),
                ('cni', models.CharField(blank=True, max_length=30, verbose_name='N° CNI')),
                ('nationalite', models.CharField(max_length=50, verbose_name='NATIONALITE')),
                ('activite', models.CharField(max_length=100, verbose_name='ACTIVITE PRINCIPALE')),
                ('compte_pal', models.CharField(max_length=30, verbose_name='N° DE COMPTE PAL')),
                ('nif', models.CharField(max_length=30, verbose_name="N° D'IDENTIFICATION FISCALE")),
                ('telephone', models.CharField(max_length=20, verbose_name='TELEPHONE MOBILE')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-MAIL')),
                ('situation_geo', models.CharField(max_length=100, verbose_name='SITUATION GEOGRAPHIQUE')),
                ('adresse_postale', models.CharField(max_length=200, verbose_name='ADRESSE POSTALE')),
                ('date_delivrance', models.DateField(auto_now_add=True, verbose_name='Présente à la date du')),
                ('agent', models.CharField(max_length=100, verbose_name='Agent')),
                ('statut', models.CharField(default='Délivré', max_length=20)),
            ],
            options={
                'verbose_name': 'Attestation de Régularité',
                'verbose_name_plural': 'Attestations de Régularité',
            },
        ),
    ]
