# Generated by Django 5.2.7 on 2025-11-10 18:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('matricule', models.CharField(max_length=50, unique=True, verbose_name='Matricule')),
                ('fonction', models.CharField(max_length=100, verbose_name='Fonction')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'db_table': 'agents',
                'ordering': ['nom_complet'],
            },
        ),
        migrations.CreateModel(
            name='Quitus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_quitus', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Format invalide', regex='^[A-Z0-9\\-]+$')], verbose_name='Numéro de Quitus')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création')),
                ('date_validite', models.DateField(verbose_name='Date de validité')),
                ('date_emission', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'émission")),
                ('nom_prenoms', models.CharField(max_length=200, verbose_name='Nom et Prénoms')),
                ('raison_sociale', models.CharField(blank=True, max_length=200, null=True, verbose_name='Raison Sociale')),
                ('cni', models.CharField(max_length=50, verbose_name='N° CNI')),
                ('nationalite', models.CharField(default='Togolaise', max_length=50, verbose_name='Nationalité')),
                ('activite', models.CharField(max_length=200, verbose_name='Activité Principale')),
                ('compte_pal', models.CharField(max_length=50, verbose_name='N° Compte PAL')),
                ('nif', models.CharField(max_length=50, verbose_name='NIF')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('situation_geo', models.CharField(max_length=300, verbose_name='Situation Géographique')),
                ('adresse_postale', models.CharField(max_length=200, verbose_name='Adresse Postale')),
                ('qr_code', models.TextField(blank=True, null=True, verbose_name='Données QR Code')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='Image QR Code')),
                ('code_verification', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Code de vérification')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='quitus_pdf/', verbose_name='Fichier PDF')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('EXPIRE', 'Expiré'), ('ANNULE', 'Annulé')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('ip_creation', models.GenericIPAddressField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quitus_app.agent', verbose_name='Agent responsable')),
            ],
            options={
                'verbose_name': 'Quitus',
                'verbose_name_plural': 'Quitus',
                'db_table': 'quitus',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueQuitus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('utilisateur', models.CharField(blank=True, max_length=200, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('quitus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='quitus_app.quitus')),
            ],
            options={
                'verbose_name': 'Historique Quitus',
                'verbose_name_plural': 'Historiques Quitus',
                'db_table': 'historique_quitus',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('EXPIRY_WARNING', "Avertissement d'expiration"), ('EXPIRY_EXPIRED', "Notification d'expiration"), ('VERIFICATION_FAILED', 'Vérification échouée'), ('SYSTEM_ALERT', 'Alerte système')], max_length=50)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyé'), ('FAILED', 'Échoué'), ('BOUNCED', 'Rejeté')], default='PENDING', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('message_text', models.TextField()),
                ('message_html', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('quitus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='quitus_app.quitus')),
            ],
            options={
                'verbose_name': 'Historique Notification',
                'verbose_name_plural': 'Historiques Notifications',
                'db_table': 'historique_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='quitus',
            index=models.Index(fields=['numero_quitus'], name='quitus_numero__5d6f2d_idx'),
        ),
        migrations.AddIndex(
            model_name='quitus',
            index=models.Index(fields=['date_creation'], name='quitus_date_cr_1e4fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='quitus',
            index=models.Index(fields=['statut'], name='quitus_statut_965e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='historiquenotifications',
            index=models.Index(fields=['status', 'created_at'], name='historique__status_540ac4_idx'),
        ),
        migrations.AddIndex(
            model_name='historiquenotifications',
            index=models.Index(fields=['recipient_email', 'status'], name='historique__recipie_7cd6b2_idx'),
        ),
    ]
