# Generated by Django 5.2.8 on 2025-11-07 16:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def forwards(apps, schema_editor):
    Quitus = apps.get_model('quitus_app', 'Quitus')
    Agent = apps.get_model('quitus_app', 'Agent')
    # For each existing Quitus row, create or get an Agent using the current agent string
    for q in Quitus.objects.all():
        name = getattr(q, 'agent')
        if name:
            a, created = Agent.objects.get_or_create(
                matricule=name,
                defaults={'nom_complet': name, 'fonction': '', 'email': '', 'telephone': ''}
            )
        else:
            a = Agent.objects.create(matricule=f'agent-{q.pk}', nom_complet=f'Agent {q.pk}', fonction='', email='', telephone='')
        q.agent_fk_id = a.pk
        q.save(update_fields=['agent_fk_id'])


def backwards(apps, schema_editor):
    Quitus = apps.get_model('quitus_app', 'Quitus')
    for q in Quitus.objects.all():
        if getattr(q, 'agent_fk', None):
            q.agent = q.agent_fk.nom_complet
            q.save(update_fields=['agent'])


class Migration(migrations.Migration):

    dependencies = [
        ('quitus_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('matricule', models.CharField(max_length=50, unique=True, verbose_name='Matricule')),
                ('fonction', models.CharField(max_length=100, verbose_name='Fonction')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'db_table': 'agents',
                'ordering': ['nom_complet'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueQuitus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('utilisateur', models.CharField(blank=True, max_length=200, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Historique Quitus',
                'verbose_name_plural': 'Historiques Quitus',
                'db_table': 'historique_quitus',
                'ordering': ['-date_action'],
            },
        ),
        migrations.AlterModelOptions(
            name='quitus',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Quitus', 'verbose_name_plural': 'Quitus'},
        ),
        migrations.RemoveField(
            model_name='quitus',
            name='date_delivrance',
        ),
        migrations.AddField(
            model_name='quitus',
            name='code_verification',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Code de vérification'),
        ),
        migrations.AddField(
            model_name='quitus',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='quitus',
            name='date_emission',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Date d'émission"),
        ),
        migrations.AddField(
            model_name='quitus',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quitus',
            name='ip_creation',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quitus',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='quitus_pdf/', verbose_name='Fichier PDF'),
        ),
        migrations.AddField(
            model_name='quitus',
            name='qr_code',
            field=models.TextField(blank=True, null=True, verbose_name='Données QR Code'),
        ),
        migrations.AddField(
            model_name='quitus',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='Image QR Code'),
        ),
        migrations.AlterField(
            model_name='quitus',
            name='activite',
            field=models.CharField(max_length=200, verbose_name='Activité Principale'),
        ),
        migrations.AlterField(
            model_name='quitus',
            name='adresse_postale',
            field=models.CharField(max_length=200, verbose_name='Adresse Postale'),
        ),
        migrations.AlterField(
            model_name='quitus',
            name='cni',
            field=models.CharField(max_length=50, verbose_name='N° CNI'),
        ),
        migrations.AlterField(
            model_name='quitus',
            name='compte_pal',
            field=models.CharField(max_length=50, verbose_name='N° Compte PAL'),
        ),
        migrations.AlterField(
            model_name='quitus',
            name='date_validite',
            field=models.DateField(verbose_name='Date de validité'),
        ),
        migrations.AlterField(
            model_name='quitus',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='quitus',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quitus',
            name='nationalite',
            field=models.CharField(default='Togolaise', max_length=50, verbose_name='Nationalité'),
        ),
        migrations.AlterField(
            model_name='quitus',
            name='nif',
            field=models.CharField(max_length=50, verbose_name='NIF'),
        ),
        migrations.AlterField(
            model_name='quitus',
            name='nom_prenoms',
            field=models.CharField(max_length=200, verbose_name='Nom et Prénoms'),
        ),
        migrations.AlterField(
            model_name='quitus',
            name='numero_quitus',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Format invalide', regex='^[A-Z0-9\\-]+$')], verbose_name='Numéro de Quitus'),
        ),
        migrations.AlterField(
            model_name='quitus',
            name='raison_sociale',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Raison Sociale'),
        ),
        migrations.AlterField(
            model_name='quitus',
            name='situation_geo',
            field=models.CharField(max_length=300, verbose_name='Situation Géographique'),
        ),
        migrations.AlterField(
            model_name='quitus',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('EXPIRE', 'Expiré'), ('ANNULE', 'Annulé')], default='ACTIF', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='quitus',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterModelTable(
            name='quitus',
            table='quitus',
        ),
        # Instead of altering the existing 'agent' CharField directly to a ForeignKey
        # we add a temporary nullable FK 'agent_fk', migrate data, then replace the old field.
        migrations.AddField(
            model_name='quitus',
            name='agent_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='quitus_app.agent', verbose_name='Agent (temp)'),
        ),

        migrations.RunPython(forwards, reverse_code=backwards),

        migrations.RemoveField(
            model_name='quitus',
            name='agent',
        ),

        migrations.RenameField(
            model_name='quitus',
            old_name='agent_fk',
            new_name='agent',
        ),

        # Finally make the FK non-nullable (matches the model definition)
        migrations.AlterField(
            model_name='quitus',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quitus_app.agent', verbose_name='Agent responsable'),
        ),
        migrations.AddIndex(
            model_name='quitus',
            index=models.Index(fields=['numero_quitus'], name='quitus_numero__5d6f2d_idx'),
        ),
        migrations.AddIndex(
            model_name='quitus',
            index=models.Index(fields=['date_creation'], name='quitus_date_cr_1e4fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='quitus',
            index=models.Index(fields=['statut'], name='quitus_statut_965e3a_idx'),
        ),
        migrations.AddField(
            model_name='historiquequitus',
            name='quitus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='quitus_app.quitus'),
        ),
    ]
