# Generated by Django 5.2.8 on 2025-11-27 18:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quitus_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenumberBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('params', models.JSONField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.CharField(blank=True, max_length=200, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Renumber Batch',
                'verbose_name_plural': 'Renumber Batches',
                'db_table': 'renumber_batch',
            },
        ),
    ]
