# Generated by Django 5.2.8 on 2025-11-12 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quitus_app', '0002_quitus_created_by_alter_quitus_agent_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quitus',
            name='agent',
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
