# Generated by Django 5.2.7 on 2025-11-10 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quitus_app', '0002_agent_historiquequitus_alter_quitus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquequitus',
            name='quitus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='quitus_app.quitus'),
        ),
    ]
