# Generated by Django 5.2.7 on 2025-11-10 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quitus_app', '0003_alter_historiquequitus_quitus'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('EXPIRY_WARNING', "Avertissement d'expiration"), ('EXPIRY_EXPIRED', "Notification d'expiration"), ('VERIFICATION_FAILED', 'Vérification échouée'), ('SYSTEM_ALERT', 'Alerte système')], max_length=50)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyé'), ('FAILED', 'Échoué'), ('BOUNCED', 'Rejeté')], default='PENDING', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('message_text', models.TextField()),
                ('message_html', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('quitus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='quitus_app.quitus')),
            ],
            options={
                'verbose_name': 'Historique Notification',
                'verbose_name_plural': 'Historiques Notifications',
                'db_table': 'historique_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='historique__status_540ac4_idx'), models.Index(fields=['recipient_email', 'status'], name='historique__recipie_7cd6b2_idx')],
            },
        ),
    ]
